name = "PairingHamiltonians"
uuid = "7c418f91-b4e2-4ebb-9133-e292c28f024b"
authors = ["SotaYoshida <syoshida@cc.utsunomiya-u.ac.jp>"]
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[compat]
Combinatorics = "1"
Glob = "1.3"
HDF5 = "0.17"
LaTeXStrings = "1.4.0"
LinearAlgebra = "1.11.0"
Plots = "1.40.9"
StatsBase = "0.34"
Test = "1.11.0"
TimerOutputs = "0.5"
julia = "1.11"
